C ********************************************************************
C NAME: Elijah Morris
C ASGT: Activity 2
C ORGN: CSUB - CMPS 3500
C FILE: neat.f
C DATE: 2/19/2022
C ********************************************************************
      DIMENSION NUMS(20)
      WRITE(6,*) 'PLEASE INPUT 15 INTEGERS, ONE AT THE TIME....'
      WRITE(6,*) 'YOU CAN STOP BY INPUTTING -1'
      IND = 1
10    READ 15, IN
15    FORMAT(I3)

C CHECKS IF THE USER HAS ENTERED -1       
      IF(IN + 1) 20,40,20
20    NUMS(IND) = IN

C STORES THE USER INPUT, UP TO 15 NUMBERS
      IF(IND - 15) 25,70,70
25    IND = IND + 1
      GOTO 10

C DECREASES THE INDEX BY 1 
40    IND = IND - 1

C PROGRAM VARIABLES
70    CUR_IND = 1
      SORTED = 1
      END_IND = IND
      IS_EMPTY = 0
C THE SORTING ALGORITHM IS REPEATED UNTIL EACH ELEMENT IS SORTED
      IF(IS_EMPTY - END_IND) 50, 110, 110
      
C BUBBLE SORTING ALGORITHM FOR SORTING THE ARRAY       
50    IF(NUMS(CUR_IND) - NUMS(CUR_IND+1)) 90,90,60
60    TEMP = NUMS(CUR_IND)
      NUMS(CUR_IND) = NUMS(CUR_IND+1)
      NUMS(CUR_IND+1) = TEMP
      SORTED = 0
90    IF(CUR_IND - (END_IND - 1)) 80,100,100
80    CUR_IND = CUR_IND + 1
      GOTO 50

C CHECKS IF THE ARRAY IS SORTED 
100   IF(SORTED) 105,105,110
105   END_IND = END_IND - 1
      GOTO 70

C PRINTS OUT THE SORTED ARRAY
110   DO 120 I=1, IND
120   PRINT 130, NUMS(I)

C FORMATS THE OUTPUT
130   FORMAT(I10)
      STOP
      END
